### PR TITLE
Add files for platformio

### PR DESCRIPTION
**Pull request by truglodite**
Create platformio.ini & .gitignore files for use with platformio. Include just 4 boards and tester for now.

### CODE REVIEW

**Comment by aster94** [comment]
Hi @truglodite thanks, i also use platformio, i guess that many people use it and would find the 'ini` file useful! Do you mind to leave the issue open a month or two? platformio 4.0 is near to go out and it could bring some breaking changes

**Comment by truglodite** [comment]
No problem, in fact I already made a change  to it. I'll just remove the pr for now and revisit after 4.0 is settled in. Thanks for the code btw... fun to play with!

**Comment by truglodite** [comment]
Waiting until PIO4.

**Comment by aster94** [comment]
I am happy you found it useful 😃
If you want we were discussing some improvements in #7 (mainly about code cleanness, right now it is not so easy to read) and the changes we made are in this branch https://github.com/aster94/logic-analyzer/tree/development

**Pull request closed without merging**
