### PR TITLE
Added the Mega version of processing and arduino code.

### PR DESCRIPTION
**Pull request by sancho11**
New navigation features added too.

### CODE REVIEW

**Comment by sancho11** [comment]
Siento el retraso, basicamente estaba muy ocupado con la universidad pero además olvide este proyecto (tengo más de un mes de estar en vacaciones, my bad). 
Ahora funciona bien.
Feliz año nuevo!

**Comment by aster94** [comment]
Hola sancho!

When I saw the code from hackster I didn't thought that there were so many changes, so for now I will mantain the pull request opened, I wouldn't like to risk to broke something. Anyway I think that the best way to handle many boards is not to have different processing scripts but just one with a few `#define`, like now, it handle the arduino UNO, stm32 and ESP8266
When I will have more time available I will use your code to add the needed defines in processing
Also, since I wrote this when I started programming I think that there could be a few errors (especially about the style) so a review would be a good idea

**Comment by sancho11** [comment]
Yes, I understand your point but the problem (or the reason because I do that) is that in the new code you can choose where you want to put every channel, you can put it one or several times in the order that you desire, or don't display it at all. You can do all this things in the pin assignment segment but since every board is different and you need to know how to make this for every one, so I didn't want overload the script with information (but perhaps there are a way),  and finally I don't know how the disposition of the pins are for the STM32 or for the ESP8266. But shouldn't be a problem if I look Internet I suppose...
Anyway my commit will not change any script it only add some scripts with code with my modifications. So if you have time you could try it!

Give me a day to merge the Arduino UNO and Arduino Mega in one script with definitions as you want.

**Comment by sancho11** [comment]
Well my commit modify one script, the Arduino Mega code.

**Comment by aster94** [comment]
> ... in the new code you can choose where you want to put every channel, you can put it one or several times in the order that you desire, or don't display it at all ...

This is a good idea! but unfortunatelly [this](https://github.com/sancho11/logic-analyzer/blob/master/Computer_Interface/processing_for_MEGA.pde#L106) applies only to arduino boards (and more precisely only on AVR) so for ESP8266 and STM32 it won't work (I may be wrong)

I think that if we want the correct pin names for all the boards unfortunatelly the redundancy is needed :( (I hate it also)

**Comment by aster94** [comment]
> How i said a some months ago Im really proud of the improvements. I will paste here what I put in hackster that day, because is not only an Arduino Mega Integration, actually that is the less.

You are right sancho, now I see that that there is way more 👍 

I made a new branch where we can work for the corrections
I will accept this pull request immediately and update some small fixes i did

We need to decide which formattation of the code we will keep because it is becoming a mess of whitespaces, wrong indentation ecc. Which IDE are you using for processing and which one for arduino?
I am using vscode for arduino and the default formatting and for processing the default IDE but the default formatting is not very good, maybe is better to use all on vscode this way the formatting between arduino and processing will be the same

I also made a todo list
- [ ] formatting
- [x] use of `pinMode` and `digitalWrite` outside time-critical task. This will improve readability and won't change the efficency
- [x] use of the `LED_BUILTIN` for readability and easier port to new boards
- [ ] pass the number of samples directly from processing (this way we won't need to modify the MCU sketches, all the configuration will be in processing)
- [ ] in the code comments use english
- [ ] the steps of the mouse wheel when we are in a deep zoom is too big, we should change the steps according to the `reducer`


What do you think about?

**Pull request merged**
